version: "2"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ChatServer
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
